# soru 1

In [1]:
from sympy.stats import FiniteRV, P, E, variance

In [5]:
sympy_pmf={0:0.39, 1:0.47, 2:0.13, 3:0.008}
X=FiniteRV('X', sympy_pmf)

In [6]:
E(X)

0.754000000000000

In [7]:
variance(X)

0.492346968000000

In [11]:
from sympy.stats import Hypergeometric, density, E, Variance

In [9]:
X = Hypergeometric('X', 16, 4, 3)

In [10]:
density(X).dict

{0: 11/28, 1: 33/70, 2: 9/70, 3: 1/140}

In [12]:
E(X)

3/4

In [13]:
variance(X)

39/80

In [14]:
import numpy as np

from scipy.stats import hypergeom

In [31]:
[M, n, N] = [16, 3, 4]

rv = hypergeom(M, n, N)

x = np.arange(0, n+1)



In [35]:
e=hypergeom.pmf(x, M, n, N, loc=0)

In [36]:
e

array([0.39285714, 0.47142857, 0.12857143, 0.00714286])

In [37]:
v=hypergeom.var(M, n, N, loc=0)

In [38]:
v

0.4875

In [39]:
s=hypergeom.std(M, n, N, loc=0)

In [40]:
s

0.698212002188447

# soru 2

In [54]:
from sympy.stats import ContinuousRV, P, E

from sympy import exp, Symbol, Interval, oo

x = Symbol('x')

pdf = exp(-x) # pdf of the Continuous Distribution

Z = ContinuousRV(x, pdf, set=Interval(0, 30))

E(Z)

1 - 31*exp(-30)

In [47]:
from sympy.stats import Uniform, density, P, E, variance
from sympy import Symbol, pprint

In [51]:
a=0
b=30
X = Uniform("x", a, b)

In [52]:
E(X)

15

In [55]:
var(X)

NameError: name 'var' is not defined

In [68]:
import numpy as np
from scipy.stats import uniform

In [69]:
x = np.arange(0, 30, 1)

In [86]:
uniform.mean(loc=0,scale=30)

15.0

In [81]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [87]:
uniform.cdf(np.arange(0,10,1),loc=0,scale=10)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [89]:
uniform.cdf(np.arange(24,30,1),loc=24,scale=7)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571])

# soru 5

In [90]:
import pandas as pd
import numpy as np

In [91]:
x=340
n=500

In [92]:
t=x/y

In [93]:
t

0.68

In [94]:
se_x = np.sqrt(t * (1 - t) / n)

In [95]:
se_x

0.2693201316896554

In [97]:
z_score =1.96

In [98]:
lcb = t - z_score* se_x #lower limit of the CI
ucb = t + z_score* se_x #upper limit of the CI

In [99]:
lcb

0.1521325418882754

In [100]:
ucb

1.2078674581117248